@startuml Casos de uso football
left to right direction

package FootbalLogger {
  usecase "Login" as Login
  usecase "Listar partidos" as LP
  usecase "Ver partido" as AP
  usecase "Leer eventos del partido" as REP

  usecase "Agregar evento" as CE
  usecase "Crear partido" as CP
  usecase "Concluir partido" as CLP
}

User <|-u- Admin

User ---> (Login)
User ---> (AP)
User ---> (REP)
User ---> (LP)

Admin ---> (CE)
Admin ---> (CP)
Admin ---> (CLP)
@enduml
