@startuml futbol

Arbitro --> Partido : Controla >
Arbitro --> Jugador: Penaliza >

Jugador --* Equipo : Forma parte de un >

Espectador --> Equipo: Anima >

Entrenador -down* Equipo : Organiza >

Jugador --|> Arquero
Jugador --|> Defensa
Jugador --|> CentroCampista
Jugador --|> Delantero 

Arbitro --|> Persona
Jugador -l-|> Persona 
Espectador --|> Persona 
Entrenador --|> Persona

Torneo --|> Partido

Partido *-- Reglas : Sigue unas >
Torneo *-- Reglas : Tiene >

@enduml
