@startuml modeloDelDominio


class Editorial{
    -nombre: String
    -direccion: String
    -telefono: String
    -email: String
}
class Revista {
    -ISSN: String
    -tematica: String
}

class Volumen {
    -año: Integer
}

class Numero {
    -portada: String
    -idioma: String
}

class Articulo {
    -titulo: String
    -DOI: String
    -idioma: String
    -autor: Autor
}

abstract class Persona {
}

class Usuario extends Persona {
    -nombreUsuario: String
    -contraseña: String
}

class Autor extends Usuario {
    -ORCID: string
}

Editorial "1 " *--  "n " Revista
Revista "1 " *-- "n " Volumen
Volumen "1 " *-- "n " Numero
Numero "1 " *-- "n " Articulo

Editorial "1 " *--  " n" Usuario

@enduml