@startuml modeloDelDominio


class Editorial
class Volumen 
class Numero
abstract class Persona
class Usuario

class Revista {
    -ISSN: String
}
 
class Articulo {
    -DOI: String
}
class Autor extends Usuario {
    -ORCID: string
}

Usuario -l-|> Persona

Editorial "1 " *--  "n " Revista
Revista "1 " *-- "n " Volumen
Volumen "1 " *-- "n " Numero
Numero "1 " *-- "n " Articulo
Articulo "1 " *--  " n" Autor
Revista"1 " *--  " n" Usuario

Editorial "1 " *--  " n" Usuario

@enduml