@startuml
State Encuentro {
  [*] -> Inicio
  State reloj <<choice>>
  State Inicio
  State PeríodoIntermedio

  State Período {
    Saque --> EnJuego
    EnJuego --> Detenido
    Detenido --> Saque  
  }

  Inicio --> Saque
}

Período--> reloj : Se acabó el tiempo
reloj --> PeríodoIntermedio : Quedan períodos
reloj --> [*] : No quedan períodos

PeríodoIntermedio --> Inicio
@enduml
