@startuml

Partido  -l-> Período : Se desarrolla en un >
Partido --> Reglas : Sigue >


Partido <-r- Alineación  : Disputa <
Partido <-r- Arbitro  : Dirige <


Equipo --> Alineación : Presenta >

Jugador --> Equipo : Pertenece >


Persona <|-- Arbitro
Persona <|-- Jugador

@enduml
