@startuml

Partido  --> Período : Se desarrolla en un >

Alineacion --> Partido : Disputa >

Equipo --> Alineacion : Presenta >

Arbitro --> Partido : Dirige >

Jugador --> Equipo : Pertenece a >

Partido --> Reglas : Sigue >

Persona <|-- Arbitro
Persona <|-- Jugador

@enduml
