@startuml proyecto
/' Diagrama de Clases -> Diagrama de Objetos -> Diagrama de estados '/

class Red 
class Sistema
class Hardware
class Usuario
class Notifiacion

Red  *-l-> Sistema  : Posee >
Red *--> Hardware : Obtiene >
Red *--> Usuario : Tiene >
Red *--> Notifiacion : Realiza >

Sistema <|--o SistemaDeVigilacion
Sistema <|--o SistemaDeAlarmas

Hardware <|--o Switch
Hardware <|--o Router

Notifiacion <|..o Gmail

Usuario <|--o TecnicosInternos
Usuario <|--o TecnicosExternos

@enduml
