@startuml proyecto
/' Diagrama de Clases -> Diagrama de Objetos -> Diagrama de estados '/

class Red 
class Sistema
class Hardware
class Usuario
class Notificacion

Sistema *-l-> Red : Posee >
Sistema *--> Hardware : Obtiene >
Sistema *--> Usuario : Tiene >
Sistema *-r-> Notificacion : Realiza >

Red <|--o RedAlumnos
Red <|--o RedProfesores

Hardware <|--o Switch
Hardware <|--o Router

Notificacion <|..o Email


Usuario <|--o TecnicosInternos
Usuario <|--o TecnicosExternos

@enduml