@startuml CrearPartido

State CrearPartido{ 

  State state1 as " "
  State state2 as " "

  [*] -[#green]-> state1

  note on link 
    <b>El sistema solicita
    * Nombre del partido
    * Fecha del partido
    * Equipo A
    * Equipo B
  end note

} 

[*] -[#green]-> CrearPartido

note on link
 <b>Usuario solicita
 Crear partido
end note

state1 -[#gray]-> state2 
note on link
 <b>Usuario provee información
end note
state2 -[#green]-> [*] 

@enduml
