@startuml
object "editorialUneatlantico : Editorial" as editorial

object "autor1 : Usuario" as autor1
object "autor2 : Usuario" as autor2

object "gestor : Usuario" as gestor

object "traductor : Usuario" as traductor

object "revisor : Usuario" as revisor

object "editor : Usuario" as editor

object "revista: Revista" as revista {
ISSN="2830-8566"
}

object "volumen1: Volumen" as volumen1 

object "numero1: Numero" as numero1 


object "articulo1: Articulo" as articulo1 {
DOI="https://doi.org/10.55547/v1"
}
object "articulo2: Articulo" as articulo2 {
DOI="https://doi.org/10.45542/v1"
}
object "articulo3: Articulo" as articulo3 {
DOI="https://doi.org/10.22542/v1"
}
object "articulo4: Articulo" as articulo4 {
DOI="https://doi.org/10.11542/v2"
}
object "articulo5: Articulo" as articulo5 {
DOI="https://doi.org/10.45542/v1"
}
object "articulo6: Articulo" as articulo6 {
DOI="https://doi.org/10.7232/v1"
}
object "articulo7: Articulo" as articulo7 {
DOI="https://doi.org/10.3142/v1"
}
object "articulo8: Articulo" as articulo8 {
DOI="https://doi.org/10.7892/v1"
}


editorial -d-- revista : "Contiene >" 
revista -l-- volumen1 : "> Tiene"
volumen1 -l-- numero1 : "> Contiene"
numero1 --- articulo1 : "< Pertenece "
numero1 --- articulo2 : "< Pertenece "
numero1 --- articulo3 : "< Pertenece "
numero1 --- articulo4 : "< Pertenece "
numero1 -u-- articulo5 : "< Pertenece "
numero1 -u-- articulo6 : "< Pertenece "
numero1 -u-- articulo7 : "< Pertenece "
numero1 -u-- articulo8 : "< Pertenece "

gestor -l-- editorial : "> Gestiona"
editor -u-- revista : "> Edita articulos"
autor1 -u-- revista : "> Postula artículos"
autor2 -u-- revista : "> Postula artículos"
traductor -u-- revista : "> Traduce artículos"
revisor -u-- revista : "> Revisa calidad de artículos"

@enduml