@startuml
object "editorialUneatlantico : Editorial" as editorial

object "autor1 : Usuario" as autor1
object "autor2 : Usuario" as autor2

object "gestor : Usuario" as gestor

object "traductor : Usuario" as traductor

object "revisor : Usuario" as revisor

object "editor : Usuario" as editor

object "revista: Revista" as revista {
ISSN="2830-8566"
}

object "volumen1: Volumen" as volumen1 

object "numero1: Numero" as numero1
object "numero2: Numero" as numero2
 

'Articulos numero 1'
object "articulo1: Articulo" as articulo1n1 {
DOI="https://doi.org/10.55547/v1"
}
object "articulo2: Articulo" as articulo2n1 {
DOI="https://doi.org/10.45542/v1"
}
object "articulo3: Articulo" as articulo3n1 {
DOI="https://doi.org/10.22542/v1"
}
object "articulo4: Articulo" as articulo4n1 {
DOI="https://doi.org/10.11542/v2"
}
object "articulo5: Articulo" as articulo5n1 {
DOI="https://doi.org/10.45542/v1"
}
object "articulo6: Articulo" as articulo6n1 {
DOI="https://doi.org/10.7232/v1"
}
object "articulo7: Articulo" as articulo7n1 {
DOI="https://doi.org/10.3142/v1"
}
object "articulo8: Articulo" as articulo8n1 {
DOI="https://doi.org/10.7892/v1"
}

'Articulos numero 2'
object "articulo1: Articulo" as articulo1n2 {
DOI="https://doi.org/10.55547/v1"
}
object "articulo2: Articulo" as articulo2n2 {
DOI="https://doi.org/10.45542/v1"
}
object "articulo3: Articulo" as articulo3n2 {
DOI="https://doi.org/10.22542/v1"
}
object "articulo4: Articulo" as articulo4n2 {
DOI="https://doi.org/10.11542/v2"
}
object "articulo5: Articulo" as articulo5n2 {
DOI="https://doi.org/10.45542/v1"
}
object "articulo6: Articulo" as articulo6n2 {
DOI="https://doi.org/10.7232/v1"
}
object "articulo7: Articulo" as articulo7n2 {
DOI="https://doi.org/10.3142/v1"
}
object "articulo8: Articulo" as articulo8n2 {
DOI="https://doi.org/10.7892/v1"
}


editorial -d-- revista : "Contiene >" 
revista -d-- volumen1 : "> Tiene"
volumen1 -d-- numero1 : "> Contiene"
numero1 --- articulo1n1 : "< Pertenece "
numero1 --- articulo2n1 : "< Pertenece "
numero1 --- articulo3n1 : "< Pertenece "
numero1 --- articulo4n1 : "< Pertenece "
numero1 -u-- articulo5n1 : "< Pertenece "
numero1 -u-- articulo6n1 : "< Pertenece "
numero1 -u-- articulo7n1 : "< Pertenece "
numero1 -u-- articulo8n1 : "< Pertenece "

numero2 --- articulo1n2 : "< Pertenece "
numero2 --- articulo2n2 : "< Pertenece "
numero2 --- articulo3n2 : "< Pertenece "
numero2 --- articulo4n2 : "< Pertenece "
numero2 -u-- articulo5n2 : "< Pertenece "
numero2 -u-- articulo6n2 : "< Pertenece "
numero2 -u-- articulo7n2 : "< Pertenece "
numero2 -u-- articulo8n2 : "< Pertenece "

volumen1 -d-- numero2 : "Contiene <"

gestor -l-- editorial : "> Gestiona"
editor -u-- revista : "> Edita articulos"
autor1 -u-- revista : "> Postula artículos"
autor2 -u-- revista : "> Postula artículos"
traductor -u-- revista : "> Traduce artículos"
revisor -u-- revista : "> Revisa calidad de artículos"

@enduml