@startuml

State Partido{
  [*] -> Comienzo
  State contador <<choice>>
  State Comienzo
  State EntreTiempo


  State Tiempo{
    Saque --> EnJuego
    EnJuego--> Detenido
    Detenido --> Saque
  }

  State Penales{
    Lanzamiento --> CambioEquipo
    CambioEquipo --> Lanzamiento
  }

  Comienzo --> Saque
}

Tiempo --> contador : Se acabó el tiempo
contador --> [*] : No hay más tiempos ni penales
contador --> EntreTiempo: Hay más tiempos
contador --> Penales: Hay penales
Penales --> [*] : Se acabaron los penales

EntreTiempo --> Comienzo

@enduml