@startuml

Partido  --> Tiempo: Se juega en un >

Partido --> Reglamento : Tiene >

Medico --> Jugador: Sana >

Equipo --> Alineación : Presenta >

Arbitro --r> Partido : Controla >

Arbitro --> Jugador: Penaliza >

Alineación --> Partido : Forma parte >

Jugador --> Equipo : Pertenece >

Espectador --> Jugador : Anima >

Entrenador --u> Equipo : Organiza >


Persona <|-- Arbitro
Persona <|-- Jugador
Persona <|-- Espectador
Persona <|-- Medico
Persona <|-- Entrenador


Jugador <|-- Defensa
Jugador <|-- Delantero
Jugador <|-- Arquero
Jugador <|-- Suplente
Jugador <|-- CentroCampista

@enduml