@startuml Casos de uso football
left to right direction

package System {
  usecase "Login" as Login
  usecase "LoginOut" as LoginOut
  usecase "SolicitarDatosAlumno" as SDA

  package Gestion {
    usecase "Visualizar abandono" as VA
    usecase "Visualizar estadisticas" as VE
    usecase "Visualizar interacciones" as VI
  }
  package Seguimiento {
    usecase "Visualizar cambios de alumnos" as VC
    usecase "Gestionar alertas" as GA
    usecase "Visualizar clusters" as VCL
    usecase "Gestionar notificaciones" as GN
  }
}

actor "Gestion alta direccion" as GAD
actor "Encargados seguimientos alumnos"	as ESA

GAD --> (Login)
ESA --> (Login)
GAD --> (LoginOut)
ESA --> (LoginOut)
ESA --> (SDA)
GAD --> (SDA)


GAD --> (VA)
GAD --> (VE)
GAD --> (VI)

ESA --> (VC)
ESA --> (GA)
ESA --> (VCL)
ESA --> (GN)

@enduml