@startuml Estados
[*] --> AlumnoMatriculaMaster : El Alumno se matricula a un master

state CicloDeDatos {
AlumnoMatriculaMaster --> AlumnoGeneraDatos : El alumno interactua con el panal
AlumnoGeneraDatos  --> ProcesarDatos
ProcesarDatos --> ActualizarEstadoAlumno
ActualizarEstadoAlumno --> AlumnoGeneraDatos
ActualizarEstadoAlumno --> MostrarDatos
}


@enduml