@startuml CasosDeUso
left to right direction

actor "Tiempo" as Tiempo
actor "Gestion" as GEST
actor "Seguimiento"	as SEG


package System {

  package Procesamiento {
    usecase "Solicitar datos" as SD
    usecase "Procesar datos" as PD
    usecase "Interpretar datos" as ID
    usecase "Almacenar datos" as AD
  }
  package Seguimiento {
    usecase "Gestionar notificaciones" as GN
    usecase "Listar alumnos" as LA
    usecase "Ver alumno" as VA
  }
  package Gestion {
    usecase "Login" as Login
    usecase "LoginOut" as LoginOut
    usecase "Listar clústers" as LC
    usecase "Ver clúster" as VC
    usecase "Ver interacciones" as VI
    usecase "Ver abandono" as VAB
  }
}

Tiempo --> SD
Tiempo --> AD
Tiempo --> PD
Tiempo --> ID

GEST <|-- SEG

GEST --> (Login)
GEST --> (LoginOut)
GEST --> (LC)
GEST --> (VC)
GEST --> (VAB)
GEST --> (VI)

SEG --> (LA)
SEG --> (VA)
SEG --> (GN)


@enduml