@startuml CasosDeUso
left to right direction

actor User
actor "Gestion" as GEST
actor "Seguimiento"	as SEG
actor "Tiempo" as Tiempo

User <|-u- GEST
User <|-u- SEG

package System {

  package Comun {
    usecase "Login" as Login
    usecase "LoginOut" as LoginOut
    usecase "SolicitarDatosAlumno" as SDA
  }
  package Seguimiento {
    usecase "Visualizar abandono" as VA
    usecase "Visualizar estadisticas" as VE
    usecase "Visualizar interacciones" as VI
  }
  package Gestion {
    usecase "Visualizar cambios de alumnos" as VC
    usecase "Visualizar clusters" as VCL
    usecase "Gestionar notificaciones" as GN
  }
  package Procesamiento {
    usecase "ProcesarDatos" as PD
  }
}


User --> (Login)
User --> (LoginOut)
User --> (SDA)

SEG --> (VA)
SEG --> (VE)
SEG --> (VI)

GEST --> (VC)
GEST --> (VCL)
GEST --> (GN)


Tiempo --> PD

@enduml