@startuml CasosDeUso
left to right direction

actor User
actor "Gestion" as GEST
actor "Seguimiento"	as SEG
actor "Tiempo" as Tiempo

User <|-u- SEG
SEG <|-u- GEST

package System {

  package Comun {
    usecase "Login" as Login
    usecase "LoginOut" as LoginOut
    usecase "SolicitarDatosAlumno" as SDA
  }
  package Seguimiento {
    usecase "Visualizar estadisticas" as VE
  }
  package Gestion {
    usecase "Visualizar clusters" as VCL
    usecase "Gestionar notificaciones" as GN
  }
  package Procesamiento {
    usecase "ProcesarDatos" as PD
  }
}


User --> (Login)
User --> (LoginOut)
User --> (SDA)

SEG --> (VE)

GEST --> (VC)
GEST --> (VCL)
GEST --> (GN)


Tiempo --> PD

@enduml