@startuml CasosDeUso
left to right direction

actor User
actor "Gestion" as GEST
actor "Seguimiento"	as SEG
actor "Tiempo" as Tiempo

User <|-u- SEG
GEST <|-l- SEG

package System {

  package Comun {
    usecase "Login" as Login
    usecase "LoginOut" as LoginOut
  }
  package Seguimiento {
    usecase "Gestionar notificaciones" as GN
    usecase "VerAlumnos" as VA
  }
  package Gestion {
    usecase "Visualizar clusters" as VC
    usecase "Visualizar estadisticas" as VE
  }
  package Procesamiento {
    usecase "Procesar Datos" as PD
  }
}


User --> (Login)
User --> (LoginOut)

SEG --> (VA)
SEG --> (GN)

GEST --> (VC)
GEST --> (VE)


Tiempo --> PD

@enduml