@startuml Contexto 

State fork <<fork>>

state VisualizarEstadisticas as " " <<state>>
state VisualizarAbandono as " " <<state>>
state VisualizarInteracciones as " " <<state>>

state VisualizarCambiosDeAlumnos as " " <<state>>
state VisualizarClusters as " " <<state>>
state GestionarNotificaciones as " " <<state>>

[*] -d-> fork
fork --> VisualizarEstadisticas : Visualizar Estadisticas
fork --> VisualizarAbandono : Visualizar Abandono
fork --> VisualizarInteracciones : Visualizar Interacciones

fork --> VisualizarCambiosDeAlumnos : Visualizar Cambios de Alumnos
fork --> VisualizarClusters : Visualizar Clusters
fork --> GestionarNotificaciones : Gestionar Notificaciones


@enduml