@startuml Contexto 

State fork <<fork>>

state VerEstadisticas as " " <<state>>
state VerAlumno as " " <<state>>
state ListarClusters as " " <<state>>
state ListarAlumnos as " " <<state>>
state VerCluster as " " <<state>>
state GestionarNotificaciones as " " <<state>>
state ProcesarDatos as " " <<state>>
state Login as " " <<state>>


[*] -d-> Login : Login

Login -r-> ListarClusters : Listar clusters

ListarClusters -d-> fork

ListarClusters --> VerCluster : Ver Cluster
VerCluster --> VerAlumno : Ver Alumno


fork --> VerEstadisticas : Ver Abandono
fork --> VerEstadisticas : Ver Interacciones
fork --> ListarAlumnos : Listar Alumnos
fork --> GestionarNotificaciones : Gestionar Notificaciones
fork --> ProcesarDatos : Procesar Datos
fork --> ListarClusters : Listar clusters

ListarAlumnos --> VerAlumno : Ver Alumno




@enduml
