@startuml InterpretarDatos


State InterpretarDatos{ 

  [*] -[#green]-> AlmacenarDatos

  note on link 
    <b>El sistema interpreta datos a travez de
    <b>algoritmos de aprendizage no supervisado
    <b>que como resultado agrupara los datos en clusters
  end note

} 

ProcesarDatos-[#green]-> InterpretarDatos

AlmacenarDatos -[#green]-> [*] 

@enduml