@startuml ListarAlumnos

State ListarAlumnos

State VerListaAlumnos{ 

  State state1 as " "

  [*] -[#green]-> state1

  note on link 
    <b>El sistema muestra
    * Todos los alumnos
    <b>El sistema permite
    * Ver un alumno
    <b>El sistema permite filtrar
    * Por Nombre
    * Por Apellidos
    * Por DNI
    * Por Master 
  end note
 

} 

ListarAlumnos-[#green]-> VerListaAlumnos

note on link
 <b>Usuario requiere
 Listar alumnos
end note

state1 -[#green]-> [*] 


@enduml
