@startuml ListarClusters

State Login

State VerListaClusters{ 

  State state1 as " "

  [*] -[#green]-> state1

  note on link 
    <b>El sistema muestra
    * Clústers
  end note


} 

Login-[#green]-> VerListaClusters

note on link
 <b>Usuario requiere
 Visualizar clústers
end note

state1 -[#green]-> [*] 


@enduml
