@startuml ProcesarDatos

State ProcesarDatos

State ProcesadoDeDatos{ 

  State state1 as " "

  [*] -[#green]-> state1

  note on link 
    <b>El sistema
    * Recibe datos de plataformas
    * Normaliza y procesa datos
    * Segmenta y almacena datos
  end note


} 

ProcesarDatos-[#green]-> ProcesadoDeDatos

note on link
 <b>Paso del tiempo
 Lanza procesado de datos
end note

state1 -[#green]-> [*] 


@enduml