@startuml VerAlumno

State ListarAlumno
State VerCluster

State VisualizaciónAlumno{ 

  State state1 as " "

  [*] -[#green]-> state1

  note on link 
    <b>El sistema muestra
    * Interacciones alumno

    <b>El sistema permite
    * Visualizar distintas interacciones del alumno

    <b>El sistema permite filtrar
    * Por fechas
  end note
 

} 

ListarAlumno-[#green]-> VisualizaciónAlumno
note on link
 <b>Usuario requiere
 Ver alumno
end note
VerCluster-[#green]-> VisualizaciónAlumno
note on link
 <b>Usuario requiere
 Ver alumno
end note


@enduml
