@startuml VerCluster

State ListarClusters 

State VerCluster{ 

  State state1 as " "

  state c <<choice>>

  [*] -[#green]-> state1

  note on link 
    <b>El sistema muestra
    * Lista de alumnos contenidos en ese clúster

    <b>El sistema permite filtrar
    * Por nombre 
    * Por apellidos
    * Por DNI
    * Por Master
    * Por porcentaje de abandono
  end note
 
  state1 -[#green]-> c 

  note on link 
    <b> Rol de usuario
  end note

  c -[#green]-> VerAlumno : Seguimiento

  note on link 
    <b> El sistema permite ver alumno
  end note
} 

ListarClusters -[#green]-> VerCluster

note on link
 <b>Usuario requiere
 Ver clúster
end note

c -[#red]-> [*] : Gestión


@enduml
