@startuml VerInteracciones

State VerInteracciones


State VisualizarInteracciones{ 

  State state1 as " "

  [*] -[#green]-> state1

  note on link 
    <b>El sistema muestra
    * Estadísticas interacciones
    <b>El sistema permite filtrar
    * Por fecha
    * Por iteraciones
  end note
 

} 

VerInteracciones-[#green]-> VisualizarInteracciones

note on link
 <b>Usuario requiere
 Visualizar interacciones
end note

state1 -[#green]-> [*] 


@enduml
