@startuml Detalle Caso de Uso Eliminar Número


State EliminarNúmero {

    State  " " as vacio1  
    State  "VerRevista" as vacio2  
    State  " " as vacio3 

    [*] ---> vacio1
    note on link
        **El sistema muestra **
        *Número a Eliminar
        **El sistema requiere **
        * Confirmación de Eliminación
    end note

    vacio1 -[#Green]-> vacio2
    note on link
        **El gestor confirma**
        **El sistema muestra**
        *Revista a la que pertenecia el Número
    end note

    vacio1 -[#Red]-> vacio3
    note on link
        **El gestor cancela**
        **El sistema muestra **
        *Número que no se Eliminó
    end note


}

[*] --> EliminarNúmero
note on link
    **Gestor Requiere ** 
    Eliminar Número
end note

EliminarNúmero --> [*]

@enduml