@startuml Detalle Caso de Uso Leer Revista

State LeerRevista

State VisualizarRevista {
    State " " as vacio
    [*] ---> vacio
    note on link 
    
    end note
}

LeerRevista --> VisualizarRevista  
note on link 
** Usuario Requiere ** 
Visualizar Revista
end note

 


@enduml