@startuml
left to right direction

package Competicion {

	package Partido {

		actor Configurador

		usecase CrearPartido
		usecase DefinirAlineacion
		usecase ActualizarClasificacion

		Configurador --> CrearPartido
		Configurador --> DefinirAlineacion
		Configurador --> ActualizarClasificacion


		package Encuentro {

			actor Narrador
			usecase CrearEncuentro
			usecase AñadirPeriodo

			Narrador--> CrearEncuentro
			Narrador--> AñadirPeriodo

			package Periodo {
		
				useCase AgregarEvento

				Narrador --> AgregarEvento
			}
		}
	}

	actor AdministradorCompeticion   

	usecase InscribirJugador
	usecase InscribirEquipo
    
        usecase CrearCompeticion
 
	AdministradorCompeticion   --> InscribirEquipo
	AdministradorCompeticion   --> InscribirJugador
        AdministradorCompeticion   --> CrearCompeticion

        usecase VerCompeticiones

	AdministradorCompeticion   -u-> VerCompeticiones
	Configurador -u-> VerCompeticiones
	Narrador -u-> VerCompeticiones

}	


@enduml
