@startuml proyecto

state fork_state <<fork>>

state NONAME_REDES as " "
state NONAME_USUARIOS as " "
state NONAME_DISPOSITIVOS as " "
state NONAME_ROUTERS as " "
state NONAME_CONTACTOS as " "
state NONAME_SWITCHES as " "

[*] --> Inicio
Inicio --> fork_state

'Usuarios
fork_state --> NONAME_USUARIOS: listarUsuarios
NONAME_USUARIOS --> NONAME_USUARIOS: crear usuario
NONAME_USUARIOS -up-> Inicio
'Redes
fork_state --> NONAME_REDES: listarRedes
NONAME_REDES --> NONAME_REDES: crear red
NONAME_REDES --> Red: AbrirRed
NONAME_REDES -up-> Inicio

'Contactos
Red --> NONAME_CONTACTOS: listarProveedores
NONAME_CONTACTOS --> NONAME_CONTACTOS: agregar 
NONAME_CONTACTOS --> Red

'Routers
NONAME_CONTACTOS --> NONAME_ROUTERS: listarRouters
NONAME_ROUTERS --> NONAME_ROUTERS: agregar 
NONAME_ROUTERS --> NONAME_CONTACTOS

'Switches
Red --> NONAME_SWITCHES: listarSwitches
NONAME_SWITCHES --> NONAME_SWITCHES: agregar 
NONAME_SWITCHES --> Red

'Dispositivos
NONAME_SWITCHES --> NONAME_DISPOSITIVOS: listarDispositivos
NONAME_DISPOSITIVOS --> NONAME_DISPOSITIVOS: agregar 
NONAME_DISPOSITIVOS --> NONAME_SWITCHES
@enduml
