@startuml DiagramaDeObjetos

object "Usuario : admin" as admin {
    usuario = "admin"
    contraseña = "123ABC"
    rol = "admin"
}

object "Usuario : tecnico" as user {
    usuario = "tecnico"
    contraseña = "ABC123"
    rol = "tecnico"
}

object "Notificación : Alerta" as notificacion {
    prioridad: "Alta"
    estado: "inactivo"
    mensaje: "El Sw01 se encuentra caido"
}

object "Wan : wan02" as red1 {
nombreRed = "red01"
telefonoAsociado = "123-123-123"
}

object "Router : router01" as router {
ip = "192.168.1.1"
mac = "00-B0-D0-63-C2-26"
nombre = "router01"
ubicacion = "planta 2"
}

object "Ubicacion : uneatlantico" as uneat {
nombre = "Universidad uneatlantico"
direccion= "C. Isabel Torres"
planta = "-2"
}

object "Proveedor : vodafone" as redIris {
nombre = "linea dedicada 1"
}

object "Firewall : firewall01" as firewall {
mac = "00-1B-33-22-55-H1"
nombre = "firewall01"
marca = "Pfsense"
modelo = "Y009"
ubicacion = "planta 2"
}

object "Switch : sw01" as switch {
    ip = "127.0.0.1"
    mac = "00-1B-33-22-55-H1"
    nombre = "sw01"
    modelo = "110-8T-D"
    marca = "Cisco"
}

object "Vlan : gestion" as vlan {
    ip = "127.0.10.1"
    mac = "00-1B-33-22-55-H1"
    estado = "activo"
}

object "Vlan : pdi/pass" as vlan2 {
    ip = "127.0.20.1"
    mac = "00-1B-33-22-55-H1"
    estado = "activo"
}

object "Vlan : profesores" as vlan3 {
    ip = "127.0.30.1"
    mac = "00-1B-33-22-55-H1"
    estado = "activo"
}

object "Dispositivo : antena" as DA1 {
    ip = "127.0.10.2"
    mac = "00-1B-33-22-55-H1"
    marca = "Ubiquiti"
    ubicacion = "planta 1"
    estado = "activo"
}

object "Dispositivo : cámara" as DA2 {
    ip = "127.0.10.2"
    mac = "00-1B-33-22-55-H1"
    marca = "Canon"
    ubicacion = "planta 2"
    estado = "activo"
}

object "Dispositivo : telefono voIP" as DA3{
    ip = "127.0.10.2"
    mac = "00-1B-33-22-55-H1"
    marca = "yealink"
    docenteAsiado = "docente1"
    estado = "activo"
}

object "Dispositivo : telefono voIp" as DPP1 {
    ip = "127.0.10.2"
    mac = "00-1B-33-22-55-H1"
    marca = "yealink"
    docenteAsiado = "docente1"
    estado = "activo"
}

object "Dispositivo : impresora" as DP1 {
    ip = "127.0.10.2"
    mac = "00-1B-33-22-55-H1"
    marca = "Canon"
    ubicacion = "planta 2"
    estado = "activo"
}

admin -- red1: gestiona >
admin -r- notificacion : notifica <
user -l- notificacion : notifica <
user -- red1
notificacion -- red1: crea <
red1 -- router: posee >
router -- firewall: tiene >
red1 -l- redIris: contiene >
red1 -r- uneat: está en >
firewall -- switch: posee >
switch -- vlan
switch -- vlan2
switch -- vlan3
vlan -- DA1: contiene >
vlan -- DA2
vlan -- DA3
vlan2 -- DPP1
vlan3 -- DP1

@enduml