@startuml diagramaDeEstados

State Revista{

    State Numero {
        State NumeroCreado as "Creado"
        State Selector1 <<choice>>


        State Artículo {

            State ArticuloCreado as "Creado"
            State ArticuloRevisado as "Revisado"
            State ArticuloRegistrado as "Registrado"
            State ArticuloAprobado as "Aprobado"
            State ArticuloRechazado as "Rechazado"
            State Selector2 <<choice>>

            [*] -d-> ArticuloRegistrado : Subir Artículo

            ArticuloRegistrado -d-> ArticuloRevisado : Revisar

            ArticuloRevisado -d-> Selector2
            Selector2 -d-> ArticuloAprobado : Aprobar
            Selector2 -d-> ArticuloRechazado : Rechazar


            ArticuloAprobado -u-> ArticuloCreado

            ArticuloRechazado -u-> ArticuloRegistrado : Reintentar

            ArticuloCreado -d-> Selector1 : ¿Hay 8 Artículos creados?

        }

        Selector1 --> NumeroCreado : Si los hay
        Selector1 --> ArticuloRegistrado : Si no los hay

        NumeroCreado --> Traducido : Traducir Numero
        Traducido --> [*] : Publicar Número 
         
    }
        

@enduml