@startuml diagramaDeEstados

State Revista{

    State Numero {
        
        State Artículo {

            State Selector1 <<choice>>

            State ArticuloRevisado as "Revisado"
            State ArticuloRegistrado as "Registrado"
            State ArticuloAprobado as "Aprobado"
            State ArticuloRechazado as "Rechazado"
            State Selector2 <<choice>>

            [*] -d-> ArticuloRegistrado : Subir Artículo

            ArticuloRegistrado -d-> ArticuloRevisado : Revisar

            ArticuloRevisado -d-> Selector2
            Selector2 -d-> ArticuloAprobado : Aprobar
            Selector2 -d-> ArticuloRechazado : Rechazar


            ArticuloAprobado --> Selector1 : ¿Hay 8 Artículos aprobados?

            ArticuloRechazado -u-> ArticuloRegistrado : Reintentar

            

        }
        Selector1 --> Maquetado: Si los hay, Maquetar número
        Selector1 --> ArticuloRegistrado : Si no los hay
        

        Maquetado--> ArticulosTraducidos: Traducir Artículos del número
        ArticulosTraducidos --> [*] : Publicar Número 
         
    }
}
        

@enduml