@startuml Clases

Alumno -r- Master : Se matricula en >
Alumno -- Plataforma : Interactúa >
Alumno -d- SistemaGestionUniversitario : Se registra >


Plataforma -r- SistemaGestionUniversitario : Intercambian datos

SistemaGestionUniversitario -- RecopiladorDeDatos: Solicita datos <
Plataforma -- RecopiladorDeDatos: Solicita datos <
RecopiladorDeDatos--Sistema: Solicita datos <

Sistema -- Accion : Sugiere al usuario >

@enduml
