@startuml Objetos
object "Javier Ruiz : Alumno" as Alumno{
    posibilidadAbandono: 100
}

object "Gestion Sanitaria : Master" as Master {
    modalidad: virtual
}

object "Moodle : Plataforma" as Plataforma1
object "Twitter : Plataforma" as Plataforma2
object "Facebook : Plataforma" as Plataforma3
object "GUIIA : SistemaGestionUniversitario" as SistemaGestionUniversitario
object "RecopiladorDeDatos : RecopiladorDeDatos " as RecopiladorDeDatos 
package "Sistema" #DDDDDD {
    object "ProcesadoDeDatos : ProcesadoDeDatos" as ProcesadoDeDatos
    object "Interprete : Interprete" as Interprete
    note "Envia datos procesados" as N2
}

object "EnviarCorreo : Accion" as Accion

Alumno -r- Master : Se matricula en >
Alumno -- Plataforma1 : Interactúa >
Alumno -- Plataforma2 : Interactúa >
Alumno -- Plataforma3 : Interactúa >
Alumno -d- SistemaGestionUniversitario : Se registra >

SistemaGestionUniversitario -- RecopiladorDeDatos : Solicita datos <
Plataforma1 -- RecopiladorDeDatos : Solicita datos <
Plataforma2 -- RecopiladorDeDatos : Solicita datos <
Plataforma3 -- RecopiladorDeDatos : Solicita datos <
RecopiladorDeDatos --ProcesadoDeDatos : Envia datos >
ProcesadoDeDatos -d- N2  
N2 -d- Interprete 

Interprete -d- Accion : Realiza >

@enduml
