@startuml proyecto

state NONAME_REDES as " "

state NONAME_DISPOSITIVOS as " "
state NONAME_ROUTERS as " "
state NONAME_PROVEEDORES as " "
state NONAME_SWITCHES as " "

[*] --> Inicio

'Redes
Inicio --> NONAME_REDES: listarRedes
NONAME_REDES --> NONAME_REDES: crear red
NONAME_REDES --> Red: AbrirRed
NONAME_REDES <-r- Red
NONAME_REDES -up-> Inicio

'Routers
Red --> NONAME_ROUTERS: listarRouters
NONAME_ROUTERS --> NONAME_ROUTERS: agregar 
NONAME_ROUTERS --> Red

'Proveedores
NONAME_ROUTERS --> NONAME_PROVEEDORES: listarProveedores
NONAME_PROVEEDORES --> NONAME_PROVEEDORES: agregar 
NONAME_PROVEEDORES --> NONAME_ROUTERS

'Switches
Red --> NONAME_SWITCHES: listarSwitches
NONAME_SWITCHES --> NONAME_SWITCHES: agregar 
NONAME_SWITCHES --> Red

'Dispositivos
NONAME_SWITCHES --> NONAME_DISPOSITIVOS: listarDispositivos
NONAME_DISPOSITIVOS --> NONAME_DISPOSITIVOS: agregar 
NONAME_DISPOSITIVOS --> NONAME_SWITCHES
@enduml
