@startuml proyecto

class "Red" 
class Switch
class Dispositivo
class Proveedor
class Usuario
class Seguridad

"Red" *-l- Seguridad: Tiene >
Seguridad *-- Switch: Posee >
Switch *-l- Dispositivo: Contiene >
Usuario --o "Red": Gestiona >
"Red" o-r- Proveedor  : Contiene >
"Red" o-- Edificio  : Está en >

@enduml
