@startuml proyecto

class "Router(WAN)" 
class Switch
class Dispositivo
class Contacto
class Usuario
class Seguridad

Seguridad -r-* "Router(WAN)": Posee >
Seguridad --* Switch: Tiene >
Switch -r-* Dispositivo: Contiene >
Usuario --o "Router(WAN)": Gestiona >
Contacto -l-* "Router(WAN)" : Contiene >

Usuario <|-r- Admin
Seguridad <|-l- Firewall
"Router(WAN)" <|-d- WAN1
Contacto <|-- Movistar
Switch <|-d- "Alumnos(Vlan)"
Dispositivo <|-- Ordenador
Dispositivo <|-- SistemaCamaras

@enduml
