@startuml proyecto
/' Diagrama de Clases -> Diagrama de Objetos -> Diagrama de estados '/

class Router 
class Firewall
class Switch
class Dispositivo
class Contacto
class Usuario
class Red

Red --* Router
Red --* Firewall
Red --* Switch
Red -r-* Dispositivo
Usuario --o Red
Router --* Contacto

Usuario <|-r- Admin
Red <|-l- RedAlumnos
Router <|-l- Modem
Contacto <|-- Movistar
Firewall <|-- Grupo
Switch <|-- Alumnos
Dispositivo <|-- Ordenador
Dispositivo <|-- SistemaCamaras

/'
Router -r-> Firewall
Firewall -r-> Switch
Switch --> Dispositivo
Router -l* Contacto
'/

/' Usuario --o Red '/


@enduml
