@startuml 

hide empty description

State AgregarEvento

State AgregaciónEvento{ 

  State state1 as " "
  State state2 as " "
  State state3 as " "
  State state4 as " "
  State state5 as " "


  state c <<choice>>

  [*] -[#green]-> state1

  state1-[#green]-> state2

  note on link 
    <b>El sistema permite
    * Agregar evento
        * Nombre
        * Descripción
        * Minuto
    * Finalizar creación encuentro
  end note

  state2 -[#green]-> state1
 
  note on link 
    <b>Usuario proporciona
    * Información evento
  end note

  state2 -[#green]-> state3
  
  note on link 
    <b>Usuario requiere
    * Agregar evento
  end note

  state3 -[#green]-> c

  c -[#green]-> state4

  state4 -[#green]-> state1
  
  note on link 
    <b>El sistema muestra
    * Agregación evento completada
  end note

  c-[#red]-> state5

  state5 -l[#red]-> state1

  note on link 
    <b>El sistema muestra
    * Error agregar evento
  end note


} 

AgregarEvento-[#green]-> AgregaciónEvento

note on link
 <b>Usuario requiere
 Agregación evento
end note

state2 -[#green]-> [*] 

note on link
 <b>Usuario requiere
 Finalizar agregación evento
end note

@enduml
