@startuml Clases

package "Sistema" #DDDDDD {
    class ProcesadoDeDatos
    class DatosProcesados
    class Interprete
}

Alumno -r- Master : Se matricula en >
Alumno -- Plataforma : Interactúa >
Alumno -d- SistemaGestionUniversitario : Se registra >


ProcesadoDeDatos -- DatosProcesados : Procesa los datos del alumno >

Plataforma -r- SistemaGestionUniversitario : Intercambian datos

SistemaGestionUniversitario -- RecopiladorDeDatos: Solicita datos <
Plataforma -- RecopiladorDeDatos: Solicita datos <
RecopiladorDeDatos--ProcesadoDeDatos : Envía datos 
DatosProcesados -- Interprete : Se envia a >

Interprete -- Accion : Sugiere al usuario >

@enduml
