@startuml

Partido  --> Tiempo: Se juega en un >

Partido --> Reglamento : Tiene >

Equipo --> Alineación : Presenta >

Arbitro --r> Partido : Controla >

Arbitro --> Jugador: Penaliza >

Alineación --> Partido : Forma parte >

Jugador --> Equipo : Forma parte de un >

Espectador --> Equipo: Anima >

Entrenador --u> Equipo : Organiza >

Jugador --|> Defensa
Jugador --|> Arquero
Jugador --|> Suplente
Jugador --|> CentroCampista

Jugador --|> Delantero

Persona --|> Arbitro
Persona --|> Jugador
Persona --|> Espectador
Persona --|> Entrenador




@enduml