@startuml
class PartidoFutbol


PartidoFutbol -- Estadio 
PartidoFutbol -- Árbitro
PartidoFutbol -- Equipos
Árbitro -- Reglas
Estadio -- Instalaciones
Estadio -- Afición
Equipos -- Jugadores
Equipos -- CuerpoTécnico
Jugadores -- Titulares
Jugadores -- Suplentes
PartidoFutbol -- Acciones
Acciones -- Jugadores


@enduml
