@startuml

class PartidoFutbol

PartidoFutbol --> Estadio : se disputa en
PartidoFutbol <-- Árbitro : dirige
PartidoFutbol <-- Equipos : disputa
PartidoFutbol -r-> Encuentro : desarrolla
Árbitro --> Reglas : encargado hacer cumplir

Encuentro --> Periodos : tiene varios

Equipos *-- Jugadores : pertenece
Equipos *-- CuerpoTécnico : pertenece
Jugadores --> Reglas : cumplir
CuerpoTécnico --> Alineacion : presenta


@enduml
